name: "Android Kernel Builder"
description: "An action to build Android kernel using GitHub Actions"
author: "frstprjkt"

inputs:
  kernel-url:
    required: true
  kernel-branch:
    required: false
    default: "master"
  depth:
    required: false
    default: "1"

  arch:
    required: false
    default: "arm64"
  defconfig:
    required: true
  extra-args:
    required: false
  build-number:
    required: false

  ksu:
    required: false
    default: "false"
  ksu-url:
    required: false
    default: "https://github.com/tiann/KernelSU"
  ksu-version:
    required: false
    default: "main"

  aosp-clang:
    required: false
    default: "true"
  aosp-clang-version:
    required: false
    default: "r563880c"
  aosp-gcc:
    required: false
    default: "false"

  anykernel3:
    required: false
    default: "false"
  anykernel3-url:
    required: false
  anykernel3-branch:
    required: false
    default: "master"
  package-name:
    required: false
    default: "anykernel3.zip"

  artifact-upload:
    required: false
    default: "false"

  telegram-upload:
    required: false
    default: "false"
  telegram-bot-token:
    required: false
  telegram-chat-id:
    required: false
  telegram-caption:
    required: false

runs:
  using: "composite"
  steps:
    - name: "Setup build environment"
      shell: bash
      run: |
        echo "KERNEL_DIR=$HOME/kernel/${{ inputs.arch }}" >> $GITHUB_ENV
        echo "PACKAGE_NAME=${{ inputs.package-name }}" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install -y \
          binutils git make bc bison openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-certificates \
          python3 xz-utils aria2 build-essential

    - name: "Download AOSP Clang"
      if: ${{ inputs.aosp-clang == 'true' }}
      shell: bash
      run: |
        echo "Downloading AOSP Clang version ${{ inputs.aosp-clang-version }}..."
        TOOLCHAIN_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/clang-${{ inputs.aosp-clang-version }}.tar.gz"
        aria2c -x 16 -s 16 -k 1M $TOOLCHAIN_URL -o clang.tar.gz
        mkdir -p $HOME/toolchains/clang-${{ inputs.aosp-clang-version }}
        tar -xzf clang.tar.gz -C $HOME/toolchains/clang-${{ inputs.aosp-clang-version }}
        rm clang.tar.gz

    - name: "Download AOSP GCC"
      if: ${{ inputs.aosp-gcc == 'true' }}
      shell: bash
      run: |
        echo "Downloading AOSP GCC toolchain..."
        GCC64_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/android-msm-redbull-4.19-android14-qpr3.tar.gz"
        GCC32_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/heads/android-msm-redbull-4.19-android14-qpr3.tar.gz"
        aria2c -x 16 -s 16 -k 1M $GCC64_URL -o aarch64-gcc.tar.gz
        mkdir -p $HOME/toolchains/gcc-aarch64
        tar -xzf aarch64-gcc.tar.gz -C $HOME/toolchains/gcc-aarch64
        aria2c -x 16 -s 16 -k 1M $GCC32_URL -o arm32-gcc.tar.gz
        mkdir -p $HOME/toolchains/gcc-arm32
        tar -xzf arm32-gcc.tar.gz -C $HOME/toolchains/gcc-arm32
        rm aarch64-gcc.tar.gz arm32-gcc.tar.gz

    - name: "Downloading kernel source"
      shell: bash
      run: |
        echo "Cloning kernel source from ${{ inputs.kernel-url }} (branch: ${{ inputs.kernel-branch }}, depth: ${{ inputs.depth }})..."
        git clone --depth=${{ inputs.depth }} --branch=${{ inputs.kernel-branch }} ${{ inputs.kernel-url }} $KERNEL_DIR
        echo "Kernel source cloned to '$KERNEL_DIR' directory."

        echo "Extracting kernel version information..."
        echo "KERNEL_VERSION=$(grep -E '^VERSION =' "$KERNEL_DIR/Makefile" | awk '{print $3}')" >> $GITHUB_ENV
        echo "KERNEL_PATCHLEVEL=$(grep -E '^PATCHLEVEL =' "$KERNEL_DIR/Makefile" | awk '{print $3}')" >> $GITHUB_ENV
        echo "KERNEL_SUBLEVEL=$(grep -E '^SUBLEVEL =' "$KERNEL_DIR/Makefile" | awk '{print $3}')" >> $GITHUB_ENV
        echo "KERNEL_EXTRAVERSION=$(grep -E '^EXTRAVERSION =' "$KERNEL_DIR/Makefile" | awk '{print $3}')" >> $GITHUB_ENV

    - name: "Configure KernelSU"
      if: ${{ inputs.ksu == 'true' }}
      shell: bash
      run: |
        echo "Integrating KernelSU into the kernel source tree..."
        cd $KERNEL_DIR
        curl -LSs "${{ inputs.ksu-url }}/raw/${{ inputs.ksu-version }}/kernel/setup.sh" | bash -s ${{ inputs.ksu-version }}
        cd ../../..
        echo "KernelSU integrated into the kernel source."
        if [ $KERNEL_VERSION -lt 5 ]; then
          echo "Enabling KernelSU hooks..."
          echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=y" > $KERNEL_DIR/arch/${{ inputs.arch }}/configs/kernelsu.config
        else
          echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE only supported on kernels < 5.x. Expect your have manual hooks integration."
        fi

    - name: "Building Kernel"
      shell: bash
      run: |
        set -e
        echo "Kernel Version: "$KERNEL_VERSION.$KERNEL_PATCHLEVEL.$KERNEL_SUBLEVEL""$KERNEL_EXTRAVERSION""

        KERNEL_DEFCONFIG="${{ inputs.defconfig }}"
        if [ "${{ inputs.ksu }}" = "true" ]; then
          KERNEL_DEFCONFIG+=" kernelsu.config"
        fi

        if [[ -n "${{ inputs.build-number }}" ]]; then
          export BUILD_NUMBER="${{ inputs.build-number }}"
        fi

        if [ "${{ inputs.aosp-clang }}" = "true" ]; then
          echo "AOSP Clang path: $HOME/toolchains/clang-${{ inputs.aosp-clang-version }}/bin"
          export PATH=$HOME/toolchains/clang-${{ inputs.aosp-clang-version }}/bin:$PATH
        fi
        if [ "${{ inputs.aosp-gcc }}" = "true" ]; then
          echo "AOSP GCC aarch64 path: $HOME/toolchains/gcc-aarch64/bin"
          echo "AOSP GCC arm32 path: $HOME/toolchains/gcc-arm32/bin"
          export PATH=$HOME/toolchains/gcc-aarch64/bin:$HOME/toolchains/gcc-arm32/bin:$PATH
        fi

        if [[ "${{ inputs.arch }}" == "arm64" ]]; then
          BUILD_CLANG_TRIPLE="aarch64-linux-gnu-"
        elif [[ "${{ inputs.arch }}" == "arm" ]]; then
          BUILD_CLANG_TRIPLE="arm-linux-gnueabi-"
        fi

        if [ "${{ inputs.aosp-gcc }}" = "true" ]; then
          BUILD_CROSS_COMPILE=aarch64-linux-android-
          BUILD_CROSS_COMPILE_ARM32=arm-linux-androideabi-
        fi

        cd $KERNEL_DIR
        mkdir out
        echo "${GITHUB_RUN_NUMBER}" > out/.version
        echo "Starting kernel build for architecture: ${{ inputs.arch }} with defconfig: $KERNEL_DEFCONFIG"
        make -j$(nproc) ARCH=${{ inputs.arch }} O=out $KERNEL_DEFCONFIG ${{ inputs.extra-args }} all CROSS_COMPILE=$BUILD_CROSS_COMPILE CROSS_COMPILE_ARM32=$BUILD_CROSS_COMPILE_ARM32 CLANG_TRIPLE=$BUILD_CLANG_TRIPLE
        echo "Kernel build completed."
    
    - name: "Packaging Kernel"
      if: ${{ inputs.anykernel3 == 'true' }}
      shell: bash
      run: |
        set -e
        ANYKERNEL_DIR="$HOME/anykernel3"

        echo "Cloning AnyKernel3 from ${{ inputs.anykernel3-url }} (branch: ${{ inputs.anykernel3-branch }})..."
        git clone --depth=1 --branch=${{ inputs.anykernel3-branch }} ${{ inputs.anykernel3-url }} $ANYKERNEL_DIR

        echo "Clean AnyKernel3 directory..."
        rm -rf $ANYKERNEL_DIR/.git $ANYKERNEL_DIR/*.github
        find . -type f -name "placeholder" -exec sh -c 'rm -rf "$(dirname "$1")"' _ {} \;

        echo "Copying built kernel to AnyKernel3 directory..."
        cp $KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/Image.gz $ANYKERNEL_DIR/.
        # Add other necessary files like dtb, dtbo if available
        if [ -f "$KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/dtb" ]; then
          cp $KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/dtb $ANYKERNEL_DIR/.
        fi
        if [ -f "$KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/dtbo.img" ]; then
          cp $KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/dtbo.img $ANYKERNEL_DIR/.
        fi

        if [[ "${{ inputs.telegram-upload }}" == "true" ]]; then
          zip -r9q $HOME/${{ env.PACKAGE_NAME }}.zip $ANYKERNEL_DIR/*
          echo "OUTPUT_FILE=$HOME/${{ env.PACKAGE_NAME }}.zip" >> $GITHUB_ENV
        else
          echo "OUTPUT_DIR=$ANYKERNEL_DIR" >> $GITHUB_ENV
        fi

        echo "Kernel packaged successfully."
    
    - name: "Upload Kernel to Artifacts"
      if: ${{ inputs.artifact-upload == 'true' && inputs.anykernel3 == 'true' }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ env.PACKAGE_NAME }}
        path: ${{ env.OUTPUT_DIR }}
        if-no-files-found: error

    - name: "Upload Kernel to Telegram"
      if: ${{ inputs.telegram-upload == 'true' && inputs.anykernel3 == 'true' }}
      shell: bash
      run: |
        curl -v -F "chat_id=${{ inputs.telegram-chat-id }}" \
          -F document=@${{ env.OUTPUT_FILE }} \
          -F caption="${{ inputs.telegram-caption }}" \
          https://api.telegram.org/bot${{ inputs.telegram-bot-token }}/sendDocument
