name: "Android Kernel Builder"
description: "An action to build Android kernel using GitHub Actions"
author: "frstprjkt"

inputs:
  kernel-url:
    required: true
  kernel-branch:
    required: false
    default: "master"
  depth:
    required: false
    default: "1"

  arch:
    required: false
    default: "arm64"
  defconfig:
    required: true
  extra-args:
    required: false

  ksu:
    required: false
    default: "false"
  ksu-url:
    required: false
    default: "https://github.com/tiann/KernelSU"
  ksu-version:
    required: false
    default: "main"

  aosp-clang:
    required: false
    default: "true"
  aosp-clang-version:
    required: false
    default: "r563880c"
  aosp-gcc:
    required: false
    default: "false"

  anykernel3:
    required: false
    default: "false"
  anykernel3-url:
    required: false
  anykernel3-branch:
    required: false
    default: "master"
  package-name:
    required: false
    default: "anykernel3.zip"

runs:
  using: "composite"
  steps:
    - name: "Setup build environment"
      shell: bash
      run: |
        echo "KERNEL_DIR=$HOME/kernel/${{ inputs.arch }}" >> $GITHUB_ENV
        echo "OUTPUT_ZIP=$HOME/kernel/${{ inputs.package-name }}" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install -y \
          binutils git make bc bison openssl curl zip kmod cpio flex libelf-dev \
          libssl-dev libtfm-dev libc6-dev device-tree-compiler ca-certificates \
          python3 xz-utils aria2 build-essential

    - name: "Download AOSP Clang"
      if: ${{ inputs.aosp-clang == 'true' }}
      shell: bash
      run: |
        echo "Downloading AOSP Clang version ${{ inputs.aosp-clang-version }}..."
        TOOLCHAIN_URL="https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/mirror-goog-main-llvm-toolchain-source/clang-${{ inputs.aosp-clang-version }}.tar.gz"
        aria2c -x 16 -s 16 -k 1M $TOOLCHAIN_URL -o clang.tar.gz
        mkdir -p $HOME/toolchains/clang-${{ inputs.aosp-clang-version }}
        tar -xzf clang.tar.gz -C $HOME/toolchains/clang-${{ inputs.aosp-clang-version }}
        rm clang.tar.gz

    - name: "Download AOSP GCC"
      if: ${{ inputs.aosp-gcc == 'true' }}
      shell: bash
      run: |
        echo "Downloading AOSP GCC toolchain..."
        GCC64_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/heads/android12L-release.tar.gz
        GCC32_URL="https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/heads/android12L-release.tar.gz"
        aria2c -x 16 -s 16 -k 1M $GCC64_URL -o aarch64-gcc.tar.gz
        mkdir -p $HOME/toolchains/gcc-aarch64
        tar -xzf aarch64-gcc.tar.gz -C $HOME/toolchains/gcc-aarch64
        aria2c -x 16 -s 16 -k 1M $GCC32_URL -o arm32-gcc.tar.gz
        mkdir -p $HOME/toolchains/gcc-arm32
        tar -xzf arm32-gcc.tar.gz -C $HOME/toolchains/gcc-arm32
        rm aarch64-gcc.tar.gz arm32-gcc.tar.gz

    - name: "Downloading kernel source"
      shell: bash
      run: |
        echo "Cloning kernel source from ${{ inputs.kernel-url }} (branch: ${{ inputs.kernel-branch }}, depth: ${{ inputs.depth }})..."
        git clone --depth=${{ inputs.depth }} --branch=${{ inputs.kernel-branch }} ${{ inputs.kernel-url }} $KERNEL_DIR
        echo "Kernel source cloned to 'kernel-source' directory."

        echo "Extracting kernel version information..."
        echo "KERNEL_VERSION=$(grep -E '^VERSION =' "$KERNEL_DIR/Makefile" | awk '{print $3}')" >> $GITHUB_ENV
        echo "KERNEL_PATCHLEVEL=$(grep -E '^PATCHLEVEL =' "$KERNEL_DIR/Makefile" | awk '{print $3}')" >> $GITHUB_ENV
        echo "KERNEL_SUBLEVEL=$(grep -E '^SUBLEVEL =' "$KERNEL_DIR/Makefile" | awk '{print $3}')" >> $GITHUB_ENV
        echo "KERNEL_EXTRAVERSION=$(grep -E '^EXTRAVERSION =' "$KERNEL_DIR/Makefile" | awk '{print $3}')" >> $GITHUB_ENV
        echo "Kernel Version: "$KERNEL_VERSION.$KERNEL_PATCHLEVEL.$KERNEL_SUBLEVEL""$KERNEL_EXTRAVERSION""

    - name: "Configure KernelSU"
      if: ${{ inputs.ksu == 'true' }}
      shell: bash
      run: |
        echo "Integrating KernelSU into the kernel source tree..."
        cd $KERNEL_DIR
        curl -LSs "${{ inputs.ksu-url }}/raw/${{ inputs.ksu-version }}/kernel/setup.sh" | bash -s ${{ inputs.ksu-version }}
        cd ../../..
        echo "KernelSU integrated into the kernel source."
        if [ $KERNEL_VERSION -lt 5 ]; then
          echo "Enabling KernelSU hooks..."
          echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=y" > $KERNEL_DIR/arch/${{ inputs.arch }}/configs/kernelsu.config
        else
          echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE only supported on kernels < 5.x. Expect your have manual hooks integration."
        fi

    - name: "Building Kernel"
      shell: bash
      run: |
        set -e
        KERNEL_DEFCONFIG="${{ inputs.defconfig }}"
        if [ "${{ inputs.ksu }}" = "true" ]; then
          KERNEL_DEFCONFIG+=" kernelsu.config"
        fi

        if [ "${{ inputs.aosp-clang }}" = "true" ]; then
          echo "AOSP Clang path: $HOME/toolchains/clang-${{ inputs.aosp-clang-version }}/bin"
          export PATH=$HOME/toolchains/clang-${{ inputs.aosp-clang-version }}/bin:$PATH
        fi
        if [ "${{ inputs.aosp-gcc }}" = "true" ]; then
          echo "AOSP GCC aarch64 path: $HOME/toolchains/gcc-aarch64/bin"
          echo "AOSP GCC arm32 path: $HOME/toolchains/gcc-arm32/bin"
          export PATH=$HOME/toolchains/gcc-aarch64/bin:$HOME/toolchains/gcc-arm32/bin:$PATH
        fi

        cd $KERNEL_DIR
        echo "Starting kernel build for architecture: ${{ inputs.arch }} with defconfig: $KERNEL_DEFCONFIG"
        make -j$(nproc) ARCH=${{ inputs.arch }} O=out $KERNEL_DEFCONFIG ${{ inputs.extra-args }} all CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- CLANG_TRIPLE=aarch64-linux-gnu-
        echo "Kernel build completed."
    
    - name: "Packaging Kernel"
      if: ${{ inputs.anykernel3 == 'true' }}
      shell: bash
      run: |
        set -e
        ANYKERNEL_DIR="$HOME/anykernel3"

        echo "Cloning AnyKernel3 from ${{ inputs.anykernel3-url }} (branch: ${{ inputs.anykernel3-branch }})..."
        git clone --depth=1 --branch=${{ inputs.anykernel3-branch }} ${{ inputs.anykernel3-url }} $ANYKERNEL_DIR

        echo "Copying built kernel to AnyKernel3 directory..."
        cp $KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/Image.gz $ANYKERNEL_DIR/.
        # Add other necessary files like dtb, dtbo if available
        if [ -f "$KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/dtb" ]; then
          cp $KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/dtb $ANYKERNEL_DIR/.
        fi
        if [ -f "$KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/dtbo.img" ]; then
          cp $KERNEL_DIR/out/arch/${{ inputs.arch }}/boot/dtbo.img $ANYKERNEL_DIR/.
        fi

        echo "Creating flashable zip package..."
        cd $ANYKERNEL_DIR
        zip -r9 $OUTPUT_ZIP ./*

        echo "Kernel packaged successfully: $OUTPUT_ZIP"
    
    - name: "Upload Kernel"
      if: ${{ inputs.anykernel3 == 'true' }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.package-name }}
        path: ${{ env.OUTPUT_ZIP }}
        if-no-files-found: error
